# Author: Jochen Gast <jochen.gast@visinf.tu-darmstadt.de>

import random

import setproctitle as spt

LIST_OF_TITLES = [
    "Anu'arak",
    "Edward d'Eath'",
    "Gul'dan",
    "Jaqen H'ghar",
    "Kael'thas",
    "Kel'Thuzad",
    "Mal'Ganis",
    'Aang',
    'Abathur',
    'Abattâri',
    'Aberforth',
    'Adalgrim',
    'Adanedhel',
    'Adanel',
    'Admiral Crustacius',
    'Adrahil II',
    'Adûnakhôr',
    'Aegnor',
    'Agarwaen',
    'Aikanáro',
    'Aiwendil',
    'Alastor',
    'Alatar',
    'Alatáriel',
    'Albus',
    'Alcarin',
    'Aldamir',
    'Aldarion',
    'Aldaron',
    'Alecto',
    'Alexstrasza',
    'Alfred',
    'Alicia',
    'Amadeus',
    'Amandil',
    'Amelia',
    'Amlaith',
    'Amras',
    'Amroth',
    'Amrothos',
    'Amycus',
    'Anairë',
    'Anardil',
    'Ancalagon',
    'Ancalimon',
    'Ancalimë',
    'Andariel',
    'Andreth',
    'Andromeda',
    'Andróg',
    'Anducal',
    'Anfauglir',
    'Angelina',
    'Angrod',
    'Annatar',
    'Anthony',
    'Antioch',
    'Antonin',
    'Anárion',
    'Apollo',
    'Aquila',
    'Arabella',
    'Arador',
    'Araglas',
    'Aragorn',
    'Aragost',
    'Arahad II',
    'Arahael',
    'Aranarth',
    'Arantar',
    'Aranuir',
    'Araphant',
    'Araphor',
    'Arassuil',
    'Aratan',
    'Aratar',
    'Arathorn I',
    'Araval',
    'Aravir',
    'Aravorn',
    'Ardamin',
    'Aredhel',
    'Argeleb II',
    'Argon',
    'Argonui',
    'Argus',
    'Arien',
    'Arthedain',
    'Arthur',
    'Arvedui',
    'Arvegil',
    'Arveleg I',
    'Arwen',
    'Arya',
    'Asfaloth',
    'Asterix',
    'Astronomix',
    'Atanamir',
    'Atanatar I',
    'Augusta',
    'Augustus',
    'Aulë',
    'Auriel',
    'Auriga',
    'Aurora',
    'Ausir',
    'Avranc',
    'Azaghâl',
    'Azmodan',
    'Azula',
    'Balbo',
    'Baldor',
    'Balin',
    'Baragund',
    'Barahir'
    'Bard the Bowman',
    'Barliman',
    'Bartemius',
    'Bastian Balthazar Bux',
    'Bathilda',
    'Bauglir',
    'Belecthor II',
    'Beleg of Arnor',
    'Belegorn',
    'Belegund',
    'Belemir',
    'Belial',
    'Belladonna',
    'Bellatrix',
    'Benjen',
    'Beorn',
    'Beregond',
    'Bergil',
    'Bertha',
    'Berylla',
    'Berúthiel',
    'Bifur',
    'Bilbo',
    'Bill Ferny',
    'Bill the Pony',
    'Bill the Troll',
    'Blade of the Warlord',
    'Boaty McBoatface',
    'Boldog',
    'Bombur',
    'Boromir',
    'Brandir',
    'Bregolas',
    'Bregor',
    'Brienne of Tarth',
    'Bryce the King of Spice',
    'Bullroarer',
    'Caius Fatuous',
    'Caldean Sword',
    'Calembel',
    'Calimehtar',
    'Calion',
    'Calmacil',
    'Capricornus',
    'Caranthir',
    'Carcharoth',
    'Carl Conrad Coreander',
    'Cassia',
    'Cassivellaunus',
    'Castamir',
    'Celeborn',
    'Celebrindor',
    'Celebrían',
    'Celegorm',
    'Celepharn',
    'Cemendur',
    'Ceorl',
    'Cepheus',
    'Cersei',
    'Chief Vitalstatistix',
    'Cirion',
    'Ciryaher',
    'Ciryandil',
    'Ciryatan',
    'Ciryon',
    'Claudi',
    'Cleopatra',
    'Colin',
    'Cormac',
    'Cornelius',
    'Corona',
    'Corvus',
    'Curufin',
    'Curunír',
    'Cuthbert',
    'Cygnus',
    'Círdan',
    'Daario Naharis',
    'Daenerys',
    'Daeron',
    'Davos',
    'Dawlish',
    'Deckard Cain',
    'Dedalus',
    'Deep Thought',
    'Delphinus',
    'Demelza',
    'Denethor I',
    'Dernhelm',
    'Deórwine',
    'Diablo',
    'Didactylos',
    'Dobby',
    'Dogmatix',
    'Dolores',
    'Dorlas',
    'Doughnut Jimmy',
    'Dr Dan Streetmentioner',
    'Draco',
    'Draugluin',
    'Duilin',
    'Duriel',
    'Durin',
    'Dwalin',
    'Dáin II Ironfoot',
    'Déagol',
    'Déor',
    'Ecthelion of the Fountain',
    'Eddard',
    'Effrafax of Wug',
    'Egalmoth',
    'Eilinel',
    'Elanor the Fair',
    'Elbereth',
    'Eldacar of Gondor',
    'Eldarion',
    'Elemmakil',
    'Elendil',
    'Elendor',
    'Elendur of Arnor',
    'Elendur, Son of Isildur',
    'Elenna',
    'Elessar',
    'Elfhelm',
    'Elfhild',
    'Elfwine',
    'Elladan',
    'Ellaria',
    'Elphias',
    'Elrohir',
    'Elrond',
    'Elros',
    'Eluréd',
    'Elurín',
    'Elven-king',
    'Elwing',
    'Elwë',
    'Emeldir',
    'Emerië',
    'Emmeline',
    'Enelyë',
    'Eradan',
    'Erendis',
    'Erestor',
    'Eridanus',
    'Erkenbrand',
    'Eru Ilúvatar',
    'Estelmo',
    'Eärendil of Gondor',
    'Eärendil',
    'Eärendur of Andúnië',
    'Eärnil I',
    'Eärnur',
    'Eärwen',
    'Eönwë',
    'Falassion',
    'Fangorn',
    'Faramir',
    'Fastred of Greenholm',
    'Felaróf',
    'Female hobbits',
    'Fenix',
    'Fenrir',
    'Ferny, Bill',
    'Ferumbras III',
    'Filius',
    'Finarfin',
    'Finduilas of Dol Amroth',
    'Finduilas',
    'Fingolfin',
    'Finrod Felagund',
    'Finvain',
    'Finwë',
    'Fladrif',
    'Fleur',
    'Folcwine',
    'Forlong the Fat',
    'Fortinbras II',
    'Frank the Tank',
    'Fredegar',
    'Frerin',
    'Frodo',
    'Fréaláf Hildeson',
    'Fréawine',
    'Fuchur',
    'Fuinur',
    'Fulliautomatix',
    'Fundin',
    'Fëanor',
    'Fíriel',
    'Gabrielle',
    'Galador',
    'Galadriel',
    'Galdor of Gondolin',
    'Galdor of the Havens',
    'Galdor the Tall',
    'Gamil Zirak',
    'Gamling',
    'Gandalf',
    'Garrick',
    'Garrosh',
    'Gellert',
    'Gemini',
    'Geoffrey',
    'Geriatrix',
    'Gerontius',
    'GhânburiGhân',
    'Gilderoy',
    'Gildor Inglorion',
    'Gilgalad',
    'Gilrain',
    'Gimilkhâd',
    'Gimilzôr',
    'Gimli',
    'Ginglith',
    'Girion',
    'Glanhír',
    'Glaurung',
    'Glorfindel',
    'Gluteus Maximus',
    'Glóin',
    'Glóredhel',
    'Godric',
    'Goldberry',
    'Goldwine',
    'Golfimbul',
    'Gollum',
    'Googleplex Starthinker',
    'Gorbag',
    'Gorlim',
    'Gormadoc',
    'Gorthaur',
    'Gothmog',
    'Goyle',
    'Gracchus Armisurplus',
    'Graham',
    'Grand Maester Pycelle',
    'Gregorovitch',
    'Gregory',
    'Grimbold',
    'Griselda',
    'Grishnákh',
    'Grunthos the Flatulent',
    'Guybrush Threepwood',
    'Gwaihir',
    'Gwathir',
    'Gwindor',
    'Halbarad',
    'Haldir of Lórien',
    'Haleth',
    'Hallas',
    'Halmir',
    'Handir',
    'Hanzo',
    'Hardang',
    'Hareth',
    'Helena',
    'Helga',
    'Helm Hammerhand',
    'Hephaestus',
    'Hepzibah',
    'Herion',
    'Hermione',
    'Herucalmo',
    'Herumor',
    'Herunúmen',
    'Hirgon',
    'Hiril',
    'Horace',
    'Hostamir',
    'Hyarmendacil I',
    'Hydra',
    'Húrin the Tall',
    'Idril',
    'Ignotus',
    'Ilmarë',
    'Ilúvatar',
    'Iminyë',
    'Imperius',
    'Imrahil',
    'Inglor',
    'Ingwë',
    'Inziladûn',
    'Inzilbêth',
    'Irimë',
    'Iroh',
    'Isabella',
    'Isildur',
    'Isilmo',
    'Isilmë',
    'Isumbras',
    'Ivriniel',
    'Izual',
    'Jenny from the block',
    'Katara',
    'Kerrigan',
    'Khamûl',
    'Kharazim',
    'Khîm',
    'Kingsley',
    'Kíli',
    'Lady Cynthy Fitzmelton',
    'Lady Tedwina Slowsby',
    'Lagduf',
    'Lalaith',
    'Lavender',
    'Legolas',
    'Lenwë',
    'Leonard of Quirm',
    'Lin Beifong',
    'Lindir',
    'Lobelia',
    'Lotho',
    'Lothíriel',
    'Lt. Morales',
    'Lucius',
    'Lugdush',
    'Luna',
    'Lunara',
    'Léod',
    'Léofa',
    'Lúthien',
    'Mablung',
    'Maedhros',
    'Maeglin',
    'Maester Luwin',
    'Mafalda',
    'Maggot',
    'Maglor',
    'Magnumopus',
    'Magor',
    'Mahtan',
    'Maiar',
    'Maiev',
    'Malbeth the Seer',
    'Malfurion',
    'Malthael',
    'Malvegil',
    'Manthor',
    'Manwë',
    'Mardil Voronwë',
    'Margaery',
    'Margarethe',
    'Marietta',
    'Marjorie',
    'Marvolo',
    'Mauhúr',
    'Medivh',
    'Meleth',
    'Melian',
    'Melisandre',
    'Meneldil',
    'Meneldur, Tar',
    'Mephisto',
    'Mephistopheles',
    'Meriadoc Brandybuck',
    'Merope',
    'Millicent',
    'Minalcar',
    'Minardil',
    'Minastir',
    'Minerva',
    'Minyatur',
    'Mithrandir',
    'Morgoth',
    'Morpheus',
    'Morwen Steelsheen',
    'Morwen',
    'Mr. Shmarty Pants',
    'Muffin Man',
    'Mundungus',
    'Muradin',
    'Muzgash',
    'Myrtle',
    'Míriel Arzimraphel',
    'Míriel Serindë',
    'Nahar',
    'Narcissa',
    'Narmacil II',
    'Narvi',
    'Nazeebo',
    'Nerdanel',
    'Nessa',
    'Nienna',
    'Nienor',
    'Nimloth',
    'Nimrodel',
    'Nymphadora',
    'Náin I',
    'Níniel',
    'Oathkeeper',
    'Obelix',
    'Obi-Wan Kenobi',
    'Ohtar',
    'Olwë',
    'Olympe',
    'Olórin',
    'Ondoher',
    'Ophiuchus',
    'Orion',
    'Ornendil',
    'Orodreth',
    'Oromë',
    'Oropher',
    'Orophin',
    'Orphea',
    'Ostoher',
    'Padma',
    'Palantir',
    'Pallando',
    'Parvati',
    'Pegasus',
    'Pelendur',
    'Penelope',
    'Pengolodh',
    'Percival',
    'Peregrin',
    'Perseus',
    'Pervinca',
    'Petunia',
    'Pharazôn',
    'Phineas',
    'Pimpernel',
    'Pomona',
    'Poseidon',
    'Postmaster General',
    'President McAwesome',
    'Primula',
    'Quendi',
    'Qui-Gon Jinn',
    'Quirinus',
    'Rabastan',
    'Radagast',
    'Ragnaros',
    'Rakanoth',
    'Raynor',
    'Reginald',
    'Regulus',
    'Rehgar',
    'Remus',
    'Rodolphus',
    'Rolanda',
    'Romilda',
    'Rowena',
    'Rubeus',
    'Rudolph',
    'Rufus Drumknott',
    'Rufus',
    'Rían',
    'Rómendacil II',
    'Rúmil',
    'Sador',
    'Saeros',
    'Sagittarius',
    'Sakalthôr',
    'Salazar',
    'Salgant',
    'Salmar',
    'Samuro',
    'Samwell',
    'Samwise',
    'Saruman',
    'Sauron',
    'Scatha',
    'Scorpius',
    'Seamus',
    'Septima',
    'Serpens',
    'Severus',
    'Shadowfax',
    'Shagrat',
    'Shelob',
    'Silmariën',
    'Silvanus',
    'Simon the Sorcerer',
    'Singollo',
    'Siriondil',
    'Sirius',
    'Smaug',
    'Sméagol',
    'Soronto',
    'Squareonthehypotenus',
    'Strider',
    'Sturgis',
    'Surplus Dairiprodus',
    'Susan',
    'Sybill',
    'Sylvanas',
    'Súrion',
    'Tarannon Falastur',
    'Tarcil',
    'Tassadar',
    'Telchar',
    'Telemmaitë',
    'Telemnar',
    'Telperiën',
    'Telumehtar',
    'Tenzin',
    'Thengel',
    'Theodore',
    'Theon',
    'Theophania',
    'Thingol',
    'Thorfinn',
    'Thorin',
    'Thorondir',
    'Thorondor',
    'Thoros of Myr',
    'Thranduil',
    'Thráin I',
    'Thráin II',
    'Thrór',
    'Thuringwethel',
    'Théoden',
    'Théodred',
    'Théodwyn',
    'Tindomiel',
    'Tinúviel',
    'Toastmaster',
    'Toph Beifong',
    'Tormund Giantsbane',
    'Travers',
    'Treebeard',
    'Tremensdelirius',
    'Tulkas',
    'Turambar',
    'Turgon',
    'Tychus',
    'Tyrael',
    'Tyrael',
    'Tyrion',
    'Tywin',
    'Túrin II',
    'Vairë',
    'Valacar',
    'Valandil of Andúnië',
    'Valandil of Arnor',
    'Valandur',
    'Valar morghulis',
    'Vanimeldë',
    'Vardamir Nólimon',
    'Varis',
    'Vercingetorix',
    'Vernon',
    'Vidugavia',
    'Vidumavi',
    'Vincent',
    'Vinyarion',
    'Virgo',
    'Viserys',
    'Vladimir',
    'Vorondil the Hunter',
    'Voronwë',
    'Whitemane',
    'Will Whitfoot',
    'William',
    'Wilson Francesco II',
    'Winnifred',
    'Woody the Woodsmith',
    'Wormtongue',
    'Xenophilius',
    'Yavanna',
    'Ygritte',
    'Yoshua'
    'Yrel',
    'Yávien',
    'Zacharias'
    'Zagara',
    'Zaphod Beeblebrox',
    'Zarya',
    'Zeratul',
    'Zimraphel',
    'Zimrathôn',
    'Zuko',
    'Ælfwine',
    'Éomer',
    'Éomund',
    'Éothain',
    'Éothéod',
    'Éowyn',
    'Írildë',
    'Óin, Son of Gróin'
]

_ASCII = set(""" !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~""")

_REPLACE_CHARS = {
    'á': 'a',
    'â': 'a',
    'ä': 'a',
    'Æ': 'Ae',
    'é': 'e',
    'É': 'E',
    'ë': 'e',
    'í': 'i',
    'Í': 'I',
    'î': 'i',
    'Ó': 'O',
    'ó': 'o',
    'ô': 'o',
    'ö': 'o',
    'ú': 'u',
    'û': 'u',
    'ü': 'u'
}


def _cleanup(name):
    for key, value in _REPLACE_CHARS.items():
        name = name.replace(key, value)
    return name


def get_random_title():
    return random.choice(LIST_OF_TITLES)


def setproctitle(title):
    spt.setproctitle(_cleanup(title))
